-- Makeup Sales Data Analysis (MySQL)
-- Project Overview

-- This project analyzes the Makeup Sales Dataset 2025 using MySQL.
-- The goal is to explore the dataset, check data quality, 
-- and extract key business insights such as top-performing brands, 
-- product trends, revenue by country, and sales channels

-- View all data
select *
from makeup_sales_dataset_2025;

-- Count total number of records
SELECT COUNT(*) 
FROM makeup_sales_dataset_2025;

-- Check for missing dates
-- Tarih kontrolü
SELECT * 
FROM makeup_sales_dataset_2025
WHERE date IS NULL;

-- Check for invalid or negative values
-- Negatif / hatalı veri kontrolü
SELECT * 
FROM makeup_sales_dataset_2025
WHERE units_sold <= 0 
	OR revenue_usd <= 0;
    
-- Find the brand with the highest total revenue
-- En çok gelir getiren marka (brand)
-- toplamı en cok gelir getiren 
SELECT brand, round(SUM(revenue_usd),2) AS Top_Gelir
FROM makeup_sales_dataset_2025
GROUP BY brand
ORDER BY Top_Gelir DESC;

-- En çok satan ürün tipi
select * 
from makeup_sales_dataset_2025;

-- Find the most sold product type
select Product_Type, sum(Units_Sold) as en_cok_satan
from makeup_sales_dataset_2025
group by Product_Type
order by en_cok_satan desc
;

-- Total revenue generated by each country
-- Ülkelere göre toplam gelir
select Country, Round(sum(Revenue_USD),2) as ulkere_top_gelir
from makeup_sales_dataset_2025
group by country
order by ulkere_top_gelir desc
;

-- Revenue by sales channel
SELECT sales_channel, round(SUM(revenue_usd),2) satıs_kanalı
FROM makeup_sales_dataset_2025
GROUP BY sales_channel;

-- Monthly revenue analysis
-- aylık trend
select * 
from makeup_sales_dataset_2025;

select month(date) as ay, round(sum(Revenue_USD),2) as top_gelir
from makeup_sales_dataset_2025
group by ay
order by ay
;

-- Ranking sales channels by revenue
-- Ödeme yöntemi analizi
select sales_channel, round(sum(Revenue_USD),2) as top_gelir
from makeup_sales_dataset_2025
group by sales_channel
order by top_gelir desc;











